// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXTGwQ9GysGvDTZYEcsm0kiin96D7QAs',
    appId: '1:304541974332:web:8276b88da5c551ea16a839',
    messagingSenderId: '304541974332',
    projectId: 'mulreportcnd',
    authDomain: 'mulreportcnd.firebaseapp.com',
    storageBucket: 'mulreportcnd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGB7ezkqaCS-8d-bsHRaiQKeAxNuVCJs',
    appId: '1:304541974332:android:92c9bf30a5d4c06e16a839',
    messagingSenderId: '304541974332',
    projectId: 'mulreportcnd',
    storageBucket: 'mulreportcnd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2X1v6zsYvuqUyWpv-AQ1LkfWNAG14TU',
    appId: '1:304541974332:ios:af0c762b30e4476716a839',
    messagingSenderId: '304541974332',
    projectId: 'mulreportcnd',
    storageBucket: 'mulreportcnd.firebasestorage.app',
    iosBundleId: 'com.example.reportCnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2X1v6zsYvuqUyWpv-AQ1LkfWNAG14TU',
    appId: '1:304541974332:ios:af0c762b30e4476716a839',
    messagingSenderId: '304541974332',
    projectId: 'mulreportcnd',
    storageBucket: 'mulreportcnd.firebasestorage.app',
    iosBundleId: 'com.example.reportCnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDXTGwQ9GysGvDTZYEcsm0kiin96D7QAs',
    appId: '1:304541974332:web:6f23c1a1c29c584716a839',
    messagingSenderId: '304541974332',
    projectId: 'mulreportcnd',
    authDomain: 'mulreportcnd.firebaseapp.com',
    storageBucket: 'mulreportcnd.firebasestorage.app',
  );
}
